# SPDX-License-Identifier: GPL-3.0-or-later OR Commercial
"""
Generate random Keccak / SHA-3 test vectors for the C++ Verilator harness.

Output: a C++ header (random_vectors.h) defining a static array of
{message_bytes, message_len, mode, expected_digest, digest_len} records.
The harness in sim_main.cpp includes this header and runs each vector
through the DUT, comparing against the expected digest computed here by:

  * hashlib.sha3_256        for SHA3-256
  * hashlib.sha3_512        for SHA3-512
  * hashlib.shake_128(32B)  for SHAKE128 (fixed 32-byte squeeze)
  * hashlib.shake_256(64B)  for SHAKE256 (fixed 64-byte squeeze)
  * pycryptodome            for Ethereum Keccak-256

Strategy:
  * 100+ random messages drawn from a length distribution that exercises:
    - empty message
    - lengths 1..200 (covers single rate-block, two-block, partial fills)
    - random lengths in [201, 2000] (multi-block)
  * Each random message is hashed under all five modes; both the message
    bytes and the expected digest are emitted to the header.

Run: `python3 tb/gen_random_vectors.py > tb/random_vectors.h`
(invoked by `make regen_vectors`).

This script is deterministic given a fixed seed so the regenerated header
is reproducible across machines.
"""

import hashlib
import random
import sys

try:
    from Crypto.Hash import keccak as _eth_keccak
except ImportError:
    sys.stderr.write(
        "ERROR: pycryptodome not installed. Install via:\n"
        "  pip3 install pycryptodome\n"
        "(needed for Ethereum Keccak-256 reference)\n"
    )
    sys.exit(1)


MODE_SHA3_256 = 0
MODE_SHA3_512 = 1
MODE_SHAKE128 = 2
MODE_SHAKE256 = 3
MODE_ETH_K256 = 4


def hash_msg(mode: int, msg: bytes) -> str:
    if mode == MODE_SHA3_256:
        return hashlib.sha3_256(msg).hexdigest()
    if mode == MODE_SHA3_512:
        return hashlib.sha3_512(msg).hexdigest()
    if mode == MODE_SHAKE128:
        return hashlib.shake_128(msg).hexdigest(32)   # 256 bits
    if mode == MODE_SHAKE256:
        return hashlib.shake_256(msg).hexdigest(64)   # 512 bits
    if mode == MODE_ETH_K256:
        return _eth_keccak.new(digest_bits=256, data=msg).hexdigest()
    raise ValueError(f"unknown mode {mode}")


def main() -> int:
    random.seed(0xC0FFEE42)

    n_per_mode = 25     # 25 vectors per mode * 5 modes = 125 random vectors
    short_lengths = [0, 1, 32, 71, 72, 135, 136, 137, 167, 168, 169]
    # Lengths designed to land on rate boundaries:
    #   72  = SHA3-512 rate
    #   136 = SHA3-256 / SHAKE256 / ETH-Keccak-256 rate
    #   168 = SHAKE128 rate
    long_lengths = [random.randint(170, 2000)
                    for _ in range(n_per_mode - len(short_lengths))]
    base_lengths = short_lengths + long_lengths
    assert len(base_lengths) == n_per_mode

    out = sys.stdout
    out.write("// SPDX-License-Identifier: GPL-3.0-or-later OR Commercial\n")
    out.write("// AUTO-GENERATED by tb/gen_random_vectors.py.\n"
              "// Do not edit by hand; regenerate with `make regen_vectors`.\n")
    out.write("#pragma once\n")
    out.write("#include <cstdint>\n")
    out.write("#include <cstddef>\n\n")
    out.write("struct RandomVec {\n"
              "    const uint8_t* msg;\n"
              "    size_t         msg_len;\n"
              "    uint8_t        mode;        // 0..4\n"
              "    const char*    digest_hex;\n"
              "    size_t         digest_bytes;\n"
              "};\n\n")

    # Build (mode, msg_bytes, expected_digest) tuples
    records = []
    for mode in (MODE_SHA3_256, MODE_SHA3_512,
                 MODE_SHAKE128, MODE_SHAKE256, MODE_ETH_K256):
        for length in base_lengths:
            msg = bytes(random.randint(0, 255) for _ in range(length))
            digest_hex = hash_msg(mode, msg)
            digest_bytes = len(digest_hex) // 2
            records.append((mode, msg, digest_hex, digest_bytes))

    # Arena: one big flat array with all messages back-to-back.
    out.write("static const uint8_t kRandomArena[] = {\n")
    arena_pos = []
    pos = 0
    flat = bytearray()
    for _, msg, _, _ in records:
        arena_pos.append(pos)
        flat.extend(msg)
        pos += len(msg)
    flat.append(0)  # sentinel so kRandomArena + N is always valid
    for i in range(0, len(flat), 16):
        chunk = flat[i:i+16]
        out.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    out.write("};\n\n")

    # Table
    out.write("static const RandomVec kRandomVectors[] = {\n")
    for i, (mode, msg, dig, dig_bytes) in enumerate(records):
        ptr = f"kRandomArena + {arena_pos[i]}"
        out.write(f"    {{ {ptr}, {len(msg)}u, {mode}u, \"{dig}\", {dig_bytes}u }},\n")
    out.write("};\n\n")
    out.write("static constexpr size_t kRandomVectorCount ="
              " sizeof(kRandomVectors) / sizeof(kRandomVectors[0]);\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
